export const dataBoardGame = [
  { id: "123", stage: 1, isFinished: true },
  { id: "124", stage: 2, isFinished: true },
  { id: "125", stage: 3, isFinished: true },
  { id: "126", stage: 4, isFinished: true },
  { id: "127", stage: 5, isFinished: true },
  { id: "222", stage: 6, isFinished: true },
  { id: "111", stage: 7, isFinished: true },
  { id: "1127", stage: 8, isFinished: true },
  { id: "1227", stage: 9, isFinished: true },
  { id: "1237", stage: 10, isFinished: true },
  { id: "1323", stage: 1, isFinished: true },
  { id: "1324", stage: 2, isFinished: true },
  { id: "1325", stage: 3, isFinished: false },
  { id: "1236", stage: 4, isFinished: false },
  { id: "1247", stage: 5, isFinished: false },
  { id: "2522", stage: 6, isFinished: false },
  { id: "1411", stage: 7, isFinished: false },
  { id: "11327", stage: 8, isFinished: false },
  { id: "12227", stage: 9, isFinished: false },
  { id: "12337", stage: 10, isFinished: false },
  { id: "1423", stage: 1, isFinished: false },
  { id: "1224", stage: 2, isFinished: false },
  { id: "12345", stage: 3, isFinished: false },
  { id: "1226", stage: 4, isFinished: false },
  { id: "1427", stage: 5, isFinished: false },
  { id: "2222", stage: 6, isFinished: false },
  { id: "1141", stage: 7, isFinished: false },
  { id: "1r1227", stage: 8, isFinished: false },
  { id: "1e2427", stage: 9, isFinished: false },
  { id: "1w2237", stage: 10, isFinished: false },
  { id: "1w23", stage: 1, isFinished: false },
  { id: "1er24", stage: 2, isFinished: false },
  { id: "1q25", stage: 3, isFinished: false },
  { id: "12qwer6", stage: 4, isFinished: false },
  { id: "12wr7", stage: 5, isFinished: false },
  { id: "2qwer22", stage: 6, isFinished: false },
  { id: "11er1", stage: 7, isFinished: false },
  { id: "11er27", stage: 8, isFinished: false },
  { id: "1w227", stage: 9, isFinished: false },
  { id: "1r237", stage: 10, isFinished: false }
];

export const dataColor = [
  { id: "1", color: "white" },
  { id: "2", color: "red" },
  { id: "3", color: "green" },
  { id: "4", color: "blue" },
  { id: "5", color: "purple" },
  { id: "6", color: "yellow" },
  { id: "7", color: "orange" },
  { id: "11", color: "white" },
  { id: "12", color: "red" },
  { id: "13", color: "green" },
  { id: "14", color: "blue" },
  { id: "15", color: "purple" },
  { id: "16", color: "yellow" },
  { id: "17", color: "orange" },
  { id: "21", color: "white" },
  { id: "22", color: "red" },
  { id: "23", color: "green" },
  { id: "24", color: "blue" },
  { id: "25", color: "purple" },
  { id: "26", color: "yellow" },
  { id: "27", color: "orange" },
  { id: "31", color: "white" },
  { id: "32", color: "red" },
  { id: "33", color: "green" },
  { id: "34", color: "blue" },
  { id: "35", color: "purple" },
  { id: "36", color: "yellow" },
  { id: "37", color: "orange" },
  { id: "41", color: "white" },
  { id: "42", color: "red" },
  { id: "43", color: "green" },
  { id: "44", color: "blue" },
  { id: "45", color: "purple" },
  { id: "46", color: "yellow" },
  { id: "47", color: "orange" },
  { id: "51", color: "white" },
  { id: "52", color: "red" },
  { id: "53", color: "green" },
  { id: "54", color: "blue" },
  { id: "55", color: "purple" },
  { id: "56", color: "yellow" },
  { id: "57", color: "orange" },
  { id: "61", color: "white" },
  { id: "62", color: "red" },
  { id: "63", color: "green" },
  { id: "64", color: "blue" },
  { id: "65", color: "purple" },
  { id: "66", color: "yellow" },
  { id: "67", color: "orange" },
  { id: "71", color: "white" },
  { id: "72", color: "red" },
  { id: "73", color: "green" },
  { id: "74", color: "blue" },
  { id: "75", color: "purple" },
  { id: "76", color: "yellow" },
  { id: "77", color: "orange" }
];
